# Generated by Django 2.2.10 on 2020-03-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='foto',
            field=models.FileField(blank=True, upload_to='foto'),
        ),
    ]
